package mondial;
// Generated Nov 13, 2019, 8:25:35 PM by Hibernate Tools 3.2.2.GA



/**
 * CityId generated by hbm2java
 */
public class CityId  implements java.io.Serializable {


     private String name;
     private String country;
     private String province;

    public CityId() {
    }

    public CityId(String name, String country, String province) {
       this.name = name;
       this.country = country;
       this.province = province;
    }
   
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public String getProvince() {
        return this.province;
    }
    
    public void setProvince(String province) {
        this.province = province;
    }




}


