package mondial;
// Generated Nov 13, 2019, 8:25:35 PM by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;

/**
 * City generated by hbm2java
 */
public class City  implements java.io.Serializable {


     private CityId id;
     private BigDecimal population;
     private BigDecimal latitude;
     private BigDecimal longitude;
     private BigDecimal elevation;

    public City() {
    }

	
    public City(CityId id) {
        this.id = id;
    }
    public City(CityId id, BigDecimal population, BigDecimal latitude, BigDecimal longitude, BigDecimal elevation) {
       this.id = id;
       this.population = population;
       this.latitude = latitude;
       this.longitude = longitude;
       this.elevation = elevation;
    }
   
    public CityId getId() {
        return this.id;
    }
    
    public void setId(CityId id) {
        this.id = id;
    }
    public BigDecimal getPopulation() {
        return this.population;
    }
    
    public void setPopulation(BigDecimal population) {
        this.population = population;
    }
    public BigDecimal getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(BigDecimal latitude) {
        this.latitude = latitude;
    }
    public BigDecimal getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(BigDecimal longitude) {
        this.longitude = longitude;
    }
    public BigDecimal getElevation() {
        return this.elevation;
    }
    
    public void setElevation(BigDecimal elevation) {
        this.elevation = elevation;
    }




}


