package mondial;
// Generated Nov 13, 2019, 8:25:35 PM by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;

/**
 * Country generated by hbm2java
 */
public class Country  implements java.io.Serializable {


     private String code;
     private String name;
     private String capital;
     private String province;
     private BigDecimal area;
     private BigDecimal population;

    public Country() {
    }

	
    public Country(String code, String name) {
        this.code = code;
        this.name = name;
    }
    public Country(String code, String name, String capital, String province, BigDecimal area, BigDecimal population) {
       this.code = code;
       this.name = name;
       this.capital = capital;
       this.province = province;
       this.area = area;
       this.population = population;
    }
   
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getCapital() {
        return this.capital;
    }
    
    public void setCapital(String capital) {
        this.capital = capital;
    }
    public String getProvince() {
        return this.province;
    }
    
    public void setProvince(String province) {
        this.province = province;
    }
    public BigDecimal getArea() {
        return this.area;
    }
    
    public void setArea(BigDecimal area) {
        this.area = area;
    }
    public BigDecimal getPopulation() {
        return this.population;
    }
    
    public void setPopulation(BigDecimal population) {
        this.population = population;
    }




}


